@startuml

package controller{
    class SimulationController
}

package core {

  package entity {

    package day{
      class DailySimulationData
    }

    package equation{
        interface Equation
        class Rafikov
    }


    package interval{
        class Interval
        enum Effect
    }

    package population{
        class Individual
        class PopulationData
    }
  }

    package ports{
        interface RandomGenerator
        interface DailySimulationDataRepository
    }

  package usecase {
    class SolveEquationUseCase
  }
}

package infra {

  package random{
    class RandomProvider
  }

  package repository{
    class DailySimulationDataCsvRepository
  }

  class EquationFactory
  enum Equilibrium
}

core.usecase ..> core.entity : usa

@enduml